name: Build and Deploy
on:
  push:
    # NOTE:
    #   For a **project** site (username.github.io/project/), push things
    #     to the **master** branch and make sure to set the line below to
    # `   - master`; also, at the end of the file, change to `BRANCH: gh-pages`
    #
    #   For a **personal** site (username.github.io/), push things to a **dev**
    #     branch  and make sure to set the line  below to `- dev` this is
    #     because for user pages GitHub pages **requires** the deployment to be
    #     on the master branch; also, at the end of the file, change to
    #    `BRANCH: master`
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - uses: lemonarc/jekyll-action@1.0.0

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
